### ISSUE TITLE
pre-trained model of the anomaly detection network 

### ISSUE THREAD

**Issue by catchyoo** [vojirt/JSRNet#4]
Hello! 

May i get the pre-trained model of the anomaly detection network?
(checkpoint-best.pth)

please give to my e-mail.

wantyouji17@gmail.com

Thank you!!

**Comment by vojirt** [comment]
Hi, I have sent the email with the link. Cheers.

**Comment by farhadi76m** [comment]
Hello, 
I tried to run your test  code but I didn't have another checkpoint; so , may you send me to my email? 
farhadi76m@gmail.com
thank you .

**Comment by vojirt** [comment]
You need only two checkpoints, one for segmentation part (link available from the github page) and the other that I have send you link for.

**Comment by farhadi76m** [comment]
I'm a master's student and my thesis is about "image anomaly detection on
roads", in my research I'm trying to run all available codes in anomaly
segmentation.
I'm interested in your work, so that's all. I'd like to research and maybe
one day write a paper in this field. so I guess, I tell you anything about
my goal.
thank you

**Comment by chrisyan** [comment]
Hello, may I get the pre-trained model of the anomaly detection network? My email is zhiran.yan@outlook.com

**Comment by vojirt** [comment]
Hi, I recommend looking at a newer version on https://github.com/vojirt/DaCUP
it performs better and pretrained models are available for download from the github page.

**Comment by farhadi76m** [comment]
oh, I'll read it as soon, I'm highly interested to develops  your work !!! could I ask some questions later ?
